name: CI

on:
  push:
    branches: [ main ]
    paths: [ 'solid-start/**', '.github/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'solid-start/**', '.github/**' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: change dir
        run: cd ./solid-start
        
      - uses: pnpm/action-setup@v3
        name: install
        with:
          version: 8
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]
            - args: [--global, gulp, prettier, typescript]

      - name: build
        run: pnpm build
        env:
          BASE_PATH: /portfolio/solid-start/

      - name: create .nojekyll
        run: touch .output/public/.nojekyll

      - name: deploy pages
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages
          folder: .output/public