name: CI

on:
  push:
    branches: [ main ]
    paths: [ 'solid-start/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'solid-start/**' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: change dir
        run: cd ./solid-start

      - name: install
        run: pnpm i --legacy-peer-deps

      - name: build
        run: pnpm build
        env:
          BASE_PATH: /portfolio/solid-start/

      - name: create .nojekyll
        run: touch .output/public/.nojekyll

      - name: deploy pages
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages
          folder: .output/public