name: CI

on:
  push:
    branches: [ main ]
    paths: [ 'solid-start/**', '.github/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'solid-start/**', '.github/**' ]
  workflow_dispatch:
  
permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./solid-start
    steps:
      - uses: actions/checkout@v4
        
      - uses: pnpm/action-setup@v3
        name: install
        with:
          version: 8
          run_install: |
            - recursive: true
              args: [--strict-peer-dependencies]
            - args: [--global, typescript]

      - name: build
        run: pnpm build
        env:
          BASE_PATH: /portfolio

      - name: create .nojekyll
        run: |
          touch .output/public/.nojekyll

      - name: deploy pages
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages
          folder: ./solid-start/.output/public
